name: Gitleaks - Secret Scan

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare security folder
        run: mkdir -p security

      - name: Run Gitleaks (full repo scan)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            zricethezav/gitleaks:latest detect \
            --source="/repo" \
            --no-banner \
            --verbose \
            --report-format sarif \
            --report-path "/repo/security/gitleaks.sarif" || true

      - name: Verify report exists
        run: |
          echo "Files in security/:"
          ls -l security || echo " No SARIF found!"
          if [ -f "security/gitleaks.sarif" ]; then
            echo "Gitleaks report created."
          else
            echo " Gitleaks found no leaks."
          fi

      - name: Upload SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: security/gitleaks.sarif

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: security/gitleaks.sarif
