name: Gitleaks - Secret Scan

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        id: gitleaks
        with:
          args: detect --no-banner -v --report-format sarif --report-path security/gitleaks.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: security/gitleaks.sarif

      - name: Upload artifact (for download)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: security/gitleaks.sarif
