name: Container & Runtime Security - Trivy

on:
  workflow_dispatch:
  push:
    branches: [ "main", "**" ]
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t projectscgh:latest .

      - name: Prepare security folder
        run: mkdir -p security

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install wget -y
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
          trivy --version

      - name: Run Trivy config scan (Dockerfile)
        run: |
          echo "Scanning Dockerfile for misconfigurations..."
          trivy config --exit-code 1 --severity HIGH,CRITICAL --format table -o security/trivy-dockerfile.txt .

      - name: Run Trivy image scan
        run: |
          echo "Scanning Docker image for vulnerabilities..."
          trivy image --exit-code 1 --severity HIGH,CRITICAL --format table -o security/trivy-image.txt projectscgh:latest || true

      - name: Upload Trivy reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: security/

      - name: Fail job if severe issues found
        if: always()
        run: |
          if grep -q "CRITICAL" security/trivy-image.txt || grep -q "HIGH" security/trivy-dockerfile.txt; then
            echo "::error::High or Critical vulnerabilities detected."
            exit 1
          else
            echo "No critical issues found."
          fi
