name: Dynamic Application Security Testing - OWASP ZAP

on:
  workflow_dispatch:
  push:
    branches: [ "main", "**" ]
  pull_request:

jobs:
  zap-dast-scan:
    name: Run OWASP ZAP DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run vulnerable web app for testing
        run: |
          docker run -d -p 8080:8080 bkimminich/juice-shop
          echo "Wait 20s for app to start..."
          sleep 20

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a -T 60'
          fail_action: true
          allow_issue_writing: false
          docker_name: 'owasp/zap2docker-stable'

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap_scan_report.html
