name: Dynamic Application Security Testing - OWASP ZAP

on:
  workflow_dispatch:
  push:
    branches: [ "main", "**" ]
  pull_request:

jobs:
  zap-dast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project with Maven
        run: mvn clean package -DskipTests

      - name: Run Spring Boot app
        run: |
          nohup mvn spring-boot:run > app.log 2>&1 &
          echo "Waiting for app to start..."
          for i in {1..20}; do
            if curl -s http://localhost:8080 >/dev/null; then
              echo "App is up!"
              break
            fi
            echo "Still waiting... ($i/20)"
            sleep 5
          done

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a -T 60'
          fail_action: true
          allow_issue_writing: false

      - name: Upload ZAP report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap_scan_report.html
