name: Dynamic Application Security Testing - OWASP ZAP

on:
  workflow_dispatch:
  push:
    branches: [ "main", "**" ]
  pull_request:

env:
  TARGET_URL: http://localhost:8080
  ZAP_TIMEOUT_MINUTES: 20
  MEDIUM_THRESHOLD: 3
  FAIL_ON_HIGH: "true"

jobs:
  zap-dast-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Juice Shop (vulnerable app) in Docker
        run: |
          echo "Starting OWASP Juice Shop (for DAST target)..."
          docker run -d --name juice_shop_demo -p 8080:3000 bkimminich/juice-shop:latest
          echo "Waiting for Juice Shop to be ready (max 3 minutes)..."
          for i in {1..36}; do
            if curl -sSf ${TARGET_URL} >/dev/null 2>&1; then
              echo "Juice Shop is up!"
              break
            fi
            echo "Waiting... ($i/36)"
            sleep 5
          done
          curl -I --max-time 5 ${TARGET_URL} || true

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: '${{ env.TARGET_URL }}'
          cmd_options: '-a -T ${{ env.ZAP_TIMEOUT_MINUTES }}'
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap_dast_results

      - name: Normalize ZAP report filenames
        if: always()
        run: |
          echo "== Normalize ZAP report filenames =="
          ls -la || true

          # Copy các file về tên chuẩn (tùy version của action)
          if [ -f report_html.html ]; then cp -f report_html.html zap_report.html; fi
          if [ -f report_html.md ]; then cp -f report_html.md zap_report.html; fi
          if [ -f report_html.md.html ]; then cp -f report_html.md.html zap_report.html; fi
          if [ -f report_html.txt ]; then cp -f report_html.txt zap_report.html; fi
          if [ -f report.md ]; then cp -f report.md zap_report.html; fi
          if [ -f zap_scan_report.html ]; then cp -f zap_scan_report.html zap_report.html; fi
          if [ -f report_html.json ]; then cp -f report_html.json zap_report.json; fi
          if [ -f report_json.json ]; then cp -f report_json.json zap_report.json; fi

          if [ ! -f zap_report.html ]; then
            FOUND_HTML=$(find . -type f -name "*.html" | head -n 1)
            if [ -n "$FOUND_HTML" ]; then cp "$FOUND_HTML" zap_report.html; fi
          fi
          if [ ! -f zap_report.json ]; then
            FOUND_JSON=$(find . -type f -name "*.json" | head -n 1)
            if [ -n "$FOUND_JSON" ]; then cp "$FOUND_JSON" zap_report.json; fi
          fi

          echo "== After normalize =="
          ls -la

      - name: Evaluate ZAP report (fail on thresholds)
        if: always()
        run: |
          set -euo pipefail
          JSON="zap_report.json"
          HTML="zap_report.html"

          if [ ! -f "$JSON" ]; then
            echo "JSON report not found, skipping alert evaluation."
            exit 0
          fi

          echo "Counting alerts from $JSON ..."
          HIGH_COUNT=$(jq '[.site[]?.alerts[]? | select(.risk=="High")] | length' "$JSON")
          MEDIUM_COUNT=$(jq '[.site[]?.alerts[]? | select(.risk=="Medium")] | length' "$JSON")
          LOW_COUNT=$(jq '[.site[]?.alerts[]? | select(.risk=="Low")] | length' "$JSON")

          echo "High alerts: $HIGH_COUNT"
          echo "Medium alerts: $MEDIUM_COUNT"
          echo "Low alerts: $LOW_COUNT"

          if [ "${FAIL_ON_HIGH}" = "true" ] && [ "$HIGH_COUNT" -gt 0 ]; then
            echo "::error::Found $HIGH_COUNT HIGH alerts — failing job."
            exit 3
          fi

          if [ "$MEDIUM_COUNT" -ge "${MEDIUM_THRESHOLD}" ]; then
            echo "::error::Found $MEDIUM_COUNT MEDIUM alerts (threshold=${MEDIUM_THRESHOLD}) — failing job."
            exit 4
          fi

          echo "ZAP alert counts within threshold."

      - name: Upload ZAP reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            zap_report.html
            zap_report.json

      - name: Cleanup Docker
        if: always()
        run: |
          docker ps -a
          docker stop juice_shop_demo || true
          docker rm juice_shop_demo || true
