name: Dynamic Application Security Testing - OWASP ZAP

on:
  workflow_dispatch:
  push:
    branches: [ "main", "**" ]
  pull_request:

jobs:
  zap-scan:
    name: Run OWASP ZAP DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run vulnerable test app
        run: |
          docker run -d -p 8080:8080 bkimminich/juice-shop
          sleep 15  # chờ app khởi động

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-a -T 60'
          fail_action: true
          docker_name: 'owasp/zap2docker-stable'
          allow_issue_writing: false

      - name: Upload ZAP scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap_scan_report.html
