name: Dynamic Application Security Testing - OWASP ZAP

on:
  workflow_dispatch:
  push:
    branches: [ "main", "**" ]
  pull_request:

env:
  TARGET_URL: http://localhost:8080
  ZAP_TIMEOUT_MINUTES: 20
  MEDIUM_THRESHOLD: 3    
  FAIL_ON_HIGH: "true"   
jobs:
  zap-dast-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Juice Shop (vulnerable app) in Docker
        run: |
          echo "Starting OWASP Juice Shop (for DAST target)..."
          docker run -d --name juice_shop_demo -p 8080:3000 bkimminich/juice-shop:latest
          echo "Waiting for Juice Shop to be ready (max 3 minutes)..."
          for i in {1..36}; do
            if curl -sSf ${TARGET_URL} >/dev/null 2>&1; then
              echo "Juice Shop is up!"
              break
            fi
            echo "Waiting... ($i/36)"
            sleep 5
          done
          # print a short check
          curl -I --max-time 5 ${TARGET_URL} || true

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: '${{ env.TARGET_URL }}'
          cmd_options: "-a -T ${{ env.ZAP_TIMEOUT_MINUTES }}"
          fail_action: false            
          allow_issue_writing: false

      - name: List generated files
        run: |
          echo "Workspace files:"
          ls -la
          echo "Report JSON exists?"; test -f report.json && echo "report.json exists" || echo "report.json missing"
          echo "Report HTML exists?"; test -f report.html && echo "report.html exists" || echo "report.html missing"
          # Some versions write different filenames; normalize copy if necessary
          if [ -f report.json ]; then cp report.json zap_report.json; fi
          if [ -f report.html ]; then cp report.html zap_report.html; fi
          # Some older action names: report_md.html / report.md => attempt safe copies
          test -f zap_report.json && echo "zap_report.json ready" || echo "zap_report.json missing"

      - name: Evaluate ZAP report (fail on thresholds)
        if: always()
        run: |
          set -euo pipefail
          # Provide defaults
          JSON="zap_report.json"
          HTML="zap_report.html"

          if [ ! -f "$JSON" ]; then
            echo "ERROR: JSON report ($JSON) not found. Cannot evaluate alerts."
            echo "List files for debug:"; ls -la
            exit 2
          fi

          echo "Counting alerts in $JSON ..."
          # ZAP report structure: .site[].alerts[] with .risk fields typically "High"/"Medium"/"Low"/"Info"
          HIGH_COUNT=$(jq '[.site[]?.alerts[]? | select(.risk=="High")] | length' "$JSON")
          MEDIUM_COUNT=$(jq '[.site[]?.alerts[]? | select(.risk=="Medium")] | length' "$JSON")
          LOW_COUNT=$(jq '[.site[]?.alerts[]? | select(.risk=="Low")] | length' "$JSON")

          echo "High alerts: $HIGH_COUNT"
          echo "Medium alerts: $MEDIUM_COUNT"
          echo "Low alerts: $LOW_COUNT"

          # Fail policies
          if [ "${FAIL_ON_HIGH}" = "true" ] && [ "$HIGH_COUNT" -gt 0 ]; then
            echo "::error::Found $HIGH_COUNT HIGH alerts in ZAP report — failing job."
            exit 3
          fi

          if [ "$MEDIUM_COUNT" -ge "${MEDIUM_THRESHOLD}" ]; then
            echo "::error::Found $MEDIUM_COUNT MEDIUM alerts (threshold=${MEDIUM_THRESHOLD}) — failing job."
            exit 4
          fi

          echo "ZAP alert counts are within threshold. Continuing."

      - name: Upload ZAP reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            zap_report.html
            zap_report.json
            app.log || true

      - name: Cleanup Docker
        if: always()
        run: |
          docker ps -a
          docker stop juice_shop_demo || true
          docker rm juice_shop_demo || true
