name: Generate Security Report

on:
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Trivy Artifacts
        uses: actions/download-artifact@v4
        with:
          name: trivy-results
          path: .

      - name: Download Snyk Artifacts
        uses: actions/download-artifact@v4
        with:
          name: snyk-results
          path: .

      - name: Set executable permission and run report
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x generate-security-report.sh
          ./generate-security-report.sh

      - name: Upload security-report.md
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.md

      - name: Commit security report
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git pull origin main
          git add -f security-report.md
          git commit -m "🛡️ Add latest security scan report"
          git push https://x-access-token:$GH_TOKEN@github.com/PhuHuynh197/ProjectSCGH.git main
